### ISSUE TITLE
Finish OAuth config

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-forum#1]
- [x] Disable non-OAuth login methods.
- [x] Make sure the login flow is simple and clear.

**Comment by jfly** [comment]
> Disable non-OAuth login methods.

I think I did this already? There’s a “enable local logins” setting on https://forum.worldcubeassociation.org/admin/site_settings/category/login, which I set to false. NOTE: It says “This must be enabled for invites to work”, so we don’t have support for invites.

**Comment by viroulep** [comment]
Closing this too, as we're using SSO.
