### ISSUE TITLE
Automatically grant OAuth access to the forum.

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-forum#2]
Instead of showing the authorization screen, I think we should allowlist the forum automatically and redirect straight back to the forum.

**Comment by jfly** [comment]
Here are the devise docs for how to configure this: https://doorkeeper.gitbook.io/guides/configuration/skip-authorization. It looks pretty straightforward to do.

**Comment by viroulep** [comment]
I don't think this is relevant now that we use single sign on.
