### ISSUE TITLE
Automatically set usernames?

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-forum#3]
Currently, users can change their usernames. I think there's a case to be made for pseudonymous accounts, but allowing arbitrary usernames can become a moderation issue.

**Comment by viroulep** [comment]
With names/WCA IDs being displayed automatically, @danielkcsheppard was fine with letting them be user-defined.
Abuses can definitely be dealt with by moderators, if it turns out to be too much of an issue we can still revisit this choice.
