### ISSUE TITLE
Prevent users from setting usernames to WCA IDs

### ISSUE THREAD

**Issue by lgarron** [thewca/wca-forum#8]
If we allow custom usernames, we should not allow spoofing WCA IDs, since these are our default usernames right now.

**Comment by jfly** [comment]
Some not great answers over on https://meta.discourse.org/t/disabling-full-name-changes/53944/6 and https://meta.discourse.org/t/how-to-restrict-account-changes-when-authenticating-with-google/42458/8. These seem to just suggest making UI changes.

**Comment by AlbertoPdRF** [comment]
Maybe we can allow any usernames but display only full names, which are already auto-populated (but we should make them un-editable.) Relevant link: https://meta.discourse.org/t/username-vs-name/97947

**Comment by danielkcsheppard** [comment]
I've de-prioritised usernames now. Full name shows first on posts, with username next to it.
Un-editable full names (taken from WCA Profile of course) would be really useful as @AlbertoPdRF says. Possible?

**Comment by viroulep** [comment]
I'm going to mark this one as closed as person names are enforced, and WCA IDs are automatically displayed.

I'd argue that using someone else's WCA IDs as a username falls into abusing the freedom to choose a username (which kind of links this to #3), so it can be moderated and hopefully won't become too much of an issue.
